//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Project.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czytelnicy
    {
        public int id_czytelnika { get; set; }
        public string czytelnik_imie { get; set; }
        public string czytelnik_nazwisko { get; set; }

        /// <summary>
        /// Zwraca pelne info o czytelniku
        /// </summary>
        public string GetInfo()
        {
            string info = string.Empty;
            info = $"{czytelnik_imie} {czytelnik_nazwisko}"; //TODO dodac nr tel
            return info;
        }

        public virtual Wypozyczenia Wypozyczenia { get; set; }
    }
}
