//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Project.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazki()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int id_ksiazki { get; set; }
        public string nazwa { get; set; }
        public string autor_imie { get; set; }
        public string autor_nazwisko { get; set; }
        public int ilosc_ksiazek { get; set; }
        /// <summary>
        /// Zwraca nazwa ksiazki, info o autorze + ilosc
        /// </summary>
        /// <param name="option">0/null = bez ilosci 1 = z iloscia</param>
        public string GetInfo(int option = 0)
        {
            string info = string.Empty;
            info = $"{nazwa} {autor_imie} {autor_nazwisko}";
            if(option != 0)
            {
                info += $" Iloœæ: {ilosc_ksiazek}";
            }
            return info;
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
