//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Project.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WypozyczeniaView
    {
        public string czytelnik_imie { get; set; }
        public string czytelnik_nazwisko { get; set; }
        public string czytelnik_adres { get; set; }
        public System.DateTime data_wypozyczenia_od { get; set; }
        public Nullable<System.DateTime> data_ostatni_update { get; set; }
        public int aktywne { get; set; }
        public string nazwa { get; set; }
        public string autor_imie { get; set; }
        public string autor_nazwisko { get; set; }
        public string czytelnik_imie_nazwisko { get; set; }
        public int id_wypozyczenia { get; set; }
    }
}
