//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Project.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int id_wypozyczenia { get; set; }
        public int id_czytelnika { get; set; }
        public int id_ksiazki { get; set; }
        public int aktywne { get; set; }
        public System.DateTime data_wypozyczenia_od { get; set; }
        public Nullable<System.DateTime> data_ostatni_update { get; set; }
    
        public virtual Czytelnicy Czytelnicy { get; set; }
        public virtual Ksiazki Ksiazki { get; set; }
    }
}
